---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.auroa_name | dump }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: database
  lifecycle: experimental
  owner: sourcefuse
